# Generated by Django 4.1.5 on 2023-04-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_rename_name_material_matproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='matproduct',
            new_name='materialname',
        ),
    ]
