# Generated by Django 4.1.5 on 2023-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_rename_matproduct_material_materialname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
