# Generated by Django 4.1.5 on 2023-05-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0013_alter_product_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
